name: Build chiaki-ng macOSX arm64

on:
  workflow_dispatch:

jobs:
  build-mac_arm64_github:
    name: Build macOSX arm64 version Github
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install protobuf
        run: |
          pip3 install --user 'protobuf>=5,<6' --break-system-packages
      - name: Install brew dependencies
        run: |
          brew update
          brew uninstall pkgconfig || true
          brew install --force qt@6 ffmpeg pkgconfig opus openssl cmake ninja nasm protobuf@29 speexdsp libplacebo wget python-setuptools json-c miniupnpc libevent

      - name: Install sdl2-compat
        run: |
          sudo INSTALL_PREFIX=/usr/local scripts/build-sdl2-compat.sh
          sudo cp /usr/local/lib/pkgconfig/sdl2-compat.pc /usr/local/lib/pkgconfig/sdl2.pc
          sudo install -d /usr/local/share/licenses/SDL3 /usr/local/share/licenses/sdl2-compat
          sudo install -m 644 SDL3-3.4.0/LICENSE.txt /usr/local/share/licenses/SDL3/
          sudo install -m 644 sdl2-compat-2.32.64/LICENSE.txt /usr/local/share/licenses/sdl2-compat/

      - name: Configure chiaki-ng
        run: |
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCHIAKI_ENABLE_TESTS=ON -DCHIAKI_ENABLE_CLI=OFF -DCHIAKI_ENABLE_STEAMDECK_NATIVE=OFF -DCMAKE_PREFIX_PATH="$(brew --prefix)/opt/openssl@3;$(brew --prefix)/opt/qt@6;$(brew --prefix)/opt/protobuf@29"

      - name: Build chiaki-ng
        run: |
          export CPATH=$(brew --prefix)/opt/ffmpeg/include
          cmake --build build --config Release --clean-first

      - name: Test chiaki-ng
        run: ctest --test-dir build --output-on-failure --parallel 3

      - name: Deploy chiaki-ng
        run: |
          mkdir -p build/gui/chiaki.app/Contents/Resources/vulkan/icd.d
          wget https://github.com/KhronosGroup/MoltenVK/releases/download/v1.2.9/MoltenVK-macos.tar && tar xf MoltenVK-macos.tar
          cp MoltenVK/MoltenVK/dylib/macOS/* build/gui/chiaki.app/Contents/Resources/vulkan/icd.d
          python3 mac/package.py --input build/gui/chiaki.app --build-dir build \
            --output chiaki-ng.app --dependency-dir /usr/local/lib \
            --dependency-dir "$(brew --prefix)/lib" \
            --macdeployqt "$(brew --prefix)/opt/qt@6/bin/macdeployqt"
          hdiutil create -srcfolder chiaki-ng.app chiaki-ng.dmg
          codesign --force --entitlements gui/entitlements.xml --deep --sign - chiaki-ng.dmg

      - name: Upload chiaki-ng Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chiaki-ng-macos_arm64-Release
          path: chiaki-ng.dmg
          if-no-files-found: error
          retention-days: 7
